version: '3'

volumes:
  notif_postgres_data:
  static_value:

networks:
  notification_network:

services:
  notification_db:
    image: postgres:13.0-alpine
    container_name: notification_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - notif_postgres_data:/var/lib/postgresql/data/
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - notification_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"

  api-notification:
    build:
      context: ./notification_api
      dockerfile: Dockerfile
    container_name: api-notification
    restart: always
    depends_on:
      - notification_rabbitmq
    healthcheck:
      test: "curl -H 'X-Request-Id: ${AUTH_HEALTHCHECK_REQUEST_ID}' --fail http://127.0.0.1:8000/api/v1/health || exit 1"
      interval: 10s
      timeout: 10s
      retries: 3
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - notification_network
    expose:
      - "8000"

  notification-admin:
    build:
      context: ./notification_admin
      dockerfile: Dockerfile
    container_name: notification_admin
    restart: always
    depends_on:
      - api-notification
    volumes:
      - static_value:/opt/app/static/
    env_file:
      - .env
    networks:
      - notification_network
    expose:
      - "8000"


  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker-mail
    restart: always
    env_file:
      - .env
    networks:
      - notification_network
    expose:
      - "8000"
    links:
      - 'mailhog'

  notification_rabbitmq:
    image: rabbitmq:3-management
    container_name: notification_rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - notification_network
    expose:
      - "5672"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: notification_mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    env_file:
      - .env
    networks:
      - notification_network
    expose:
      - "1025"

#  scheduler:
#    build:
#      context: ./scheduler
#      dockerfile: Dockerfile
#    env_file:
#      - .env
#    depends_on:
#      - notification_db
#      - notification-admin
#      - notification_api
#    networks:
#      - notification_network
#    expose:
#      - "8000"

  notification_nginx:
    image: nginx:1.23.1-alpine
    container_name: notification_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_value:/static
    depends_on:
      - api-notification
    networks:
      - notification_network
    ports:
      - "80:80"
