# Generated by Django 4.0.4 on 2023-08-02 18:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("""CREATE SCHEMA IF NOT EXISTS "notification";"""),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
            ],
            options={
                'db_table': 'notification"."configs',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('websocket', 'Websocket'), ('sms', 'Sms')], max_length=100)),
                ('task', models.CharField(choices=[('review-reporting.v1.rated', 'Review Rated'), ('user-reporting.v1.registered', 'User Registered'), ('admin-reporting.v1.event', 'Admin')], max_length=100)),
                ('theme', models.TextField(blank=True, null=True)),
                ('template', models.TextField()),
            ],
            options={
                'db_table': 'notification"."templates',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('template_params', models.TextField(blank=True, null=True, verbose_name='template_params')),
                ('group', models.CharField(choices=[('subscribers', 'Отправить подписчикам'), ('everyone', 'Отправить всем')], max_length=50)),
                ('is_instant', models.BooleanField()),
                ('next_planned_date', models.DateTimeField(blank=True, null=True)),
                ('timing', models.CharField(choices=[('one', 'Один раз'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], max_length=50)),
                ('priority', models.CharField(choices=[('high', 'Высокий приоритет'), ('medium', 'Средний приоритет'), ('low', 'Низкий приоритет')], max_length=50)),
                ('last_processed_date', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.template')),
            ],
            options={
                'db_table': 'notification"."schedules',
            },
        ),
    ]
