@startuml
skinparam componentStyle uml2
skinparam PackageBackgroundColor #bfffc0
actor Клиент as Client #Blue
actor Менеджер as Manager #Red

component NGINX #LightGrey


component Admin_django


component Auth_API
component UGC
component Scheduler

queue "RabbitMQ" as Rabbit {
component email_queue
component websocket_queue
}

database "PostgreSQL" as notification_postgres{
component " Таблицы:\n Шаблоны отправки email \n История сообщений \n Расписание заданий" as Table
}
component "Worker\nMail" as WorkerMail
component "Worker\nWebsocket" as WorkerWebsocket
package NOTIFICATION_API {
component " FastApi_Notification\n" as FastApi_Notification

}

NGINX<-->NOTIFICATION_API
Auth_API-->FastApi_Notification: Событие о регистрации
UGC-->FastApi_Notification: "Событие \nЛайк комментария"
NOTIFICATION_API-->Rabbit: "Отправляет\n задания в очередь"
Manager-->Admin_django
Admin_django-->notification_postgres: Шаблоны email, расписания


WorkerMail-->email_queue:Забирает задания
WorkerWebsocket-->websocket_queue:Забирает задания
WorkerMail-->Client:Отправка email
WorkerMail-->Table
WorkerWebsocket-->Client:Отправка websocket
WorkerWebsocket-->Table

Scheduler<-->Table: Забирает расписание заданий
Scheduler-->FastApi_Notification: Отправляет задание в очередь
@enduml